import './globals.css'
import { Inter } from 'next/font/google'
import { Maven_Pro } from 'next/font/google'
import Navbar from './components/Navbar'
import Wrapper from './components/Wrapper'
import Footer from './components/Footer'
//import TopLabel from './components/Toplabel'
const inter = Maven_Pro({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"]
})

export const metadata = {
  title: 'Areeb E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='overflow-hidden w-screen'>
          {/* <TopLabel /> */}
        </div>
        <Wrapper>
          <Navbar />
          <div className='min-h-screen'>
            {children}
          </div>
          <Footer />
        </Wrapper>
      </body>


    </html>
  )
}